name: Validate, build and deploy
on:
  push:
    branches:
      - main

jobs:
  deploy-main-maven:
    if: "!contains(github.event.head_commit.message, '[skip-release]')"
    uses: entur/abt-gha-public/.github/workflows/maven-open-source-increment-version-and-release-to-maven-central.yml@main
    secrets: inherit
    with:
      java-version: 17

