name: Deploy legacy branch to Maven Central
on:
  workflow_dispatch

jobs:
  deploy-maven:
    uses: entur/gha-maven-central/.github/workflows/maven-publish.yml@v1
    secrets: inherit
    permissions:
      contents: write
      issues: write
    with:
      next_version: minor
      version_strategy: tag
      version_tag_prefix: legacy-v
      java_version: 25


